steps:
  - name: test
    image: node:15.4.0-alpine
    commands:
      - npm ci
      - npm test

  - name: check workspace
    image: busybox
    commands:
      - cat result | grep "oook"

  - name: a new step
    image: busybox
    commands:
      - echo "workspace is shared between steps"
      - ls
      - echo "this will be triggered via webhooks"
